name: Deploy Node Application

on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Build docker image
        run: sudo docker build -t nakandara/poruwa_backend .
      - name: Login to docker hub
        run: sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish image to docker hub
        run: sudo docker push nakandara/poruwa_backend:latest    
 
  deploy:
    needs: build
    runs-on: self-hosted 
    steps:
      - name: Pull image from docker hub
        run: docker pull nakandara/poruwa_backend:latest 
      - name: Delete old container
        run: docker rm -f nodejs-app-container  
      - name: Run Docker Container
        run: docker run -d -p 4000:4000 --name nodejs-app-container -e MONGODG_URI_PROJECTDB='${{ secrets.MONGODG_URI_PROJECTDB }}' -e MONGODG_URI_USERDB='${{ secrets.MONGODG_URI_USERDB }}' nakandara/poruwa_backend
