name: Update Backend and Restart PM2

on:
  push:
    branches:
      - master

jobs:
  update-and-restart:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pull latest changes
        run: git pull origin master

      - name: Restart PM2
        run: pm2 restart backend
